#	$NetBSD: Makefile.cmmc68,v 1.1 2024/01/01 00:00:00 cmmc68 Exp $

# Makefile for NetBSD/cmmc68

MACHINE_ARCH=m68000
USETOOLS?=	no
NEED_OWN_INSTALL_TARGET?=no
.include <bsd.own.mk>

##
## (1) port identification
##
CMMC68=		$S/arch/cmmc68
GENASSYM_CONF=	${CMMC68}/cmmc68/genassym.cf

##
## (2) compile settings
##
CPPFLAGS+=	-Dcmmc68
CFLAGS+=	-m68010 -msoft-float
AFLAGS+=	-m68010 -x assembler-with-cpp

##
## (3) libkern and compat
##
OPT_MODULAR=	%MODULAR%
KERNMISCMAKEFLAGS=	MACHINE_ARCH=${MACHINE_ARCH}

##
## (4) local objects, compile rules, and dependencies
##
# For MC68010 we don't need FPSP (that's for 68040)
MD_OBJS=	locore.o
MD_LIBS=
MD_CFILES=
MD_SFILES=	${CMMC68}/cmmc68/locore.s

locore.o: ${CMMC68}/cmmc68/locore.s assym.h
	${NORMAL_S}

.include "$S/arch/m68k/conf/Makefile.kern.m68k.inc"

##
## (5) link settings
##
LINKFORMAT=	-n
TEXTADDR?=	0x00C00000
LOADADDRESS?=	0x00C00000

KERN_LDSCRIPT?=	${S}/arch/cmmc68/conf/kern.ldscript

SYSTEM_LD_HEAD+=	@rm -f $@

LINKSCRIPT?=		-T ${KERN_LDSCRIPT}

EXTRA_KERNEL=	${KERNEL}.sym

##
## (6) port specific target dependencies
##

# depend on CPU configuration
locore.o machdep.o pmap.o trap.o: Makefile

##
## (7) misc settings
##

##
## (8) config(8) generated machinery
##
%INCLUDES

%OBJS

%CFILES

%SFILES

%LOAD

%RULES

##
## (9) port independent kernel machinery
##
.include "$S/conf/Makefile.kern.inc"

##
## (10) Appending make options.
##
%MAKEOPTIONSAPPEND
