# $NetBSD$

all_md)
	makedev std
	makedev tty00
	makedev ttyd0 ttyd1
	makedev md0
	;;

ramdisk)
	makedev std md0
	makedev ttyd0 ttyd1
	makedev ipty
	;;

ttyd[0-9]*)
	unit=${i#ttyd}
	mkdev ttyd$unit c 14 $unit 660 $u_uucp
	;;
